#!/bin/bash

set -eu

# Demonstrates the difficulty of reporting a proper exit code when referencing
# an unset variable and using a cleanup trap.
#
# If you switch from failure_without_exit_code to failure_with_exit_code in the
# main block, you'll find that the trap proxies the error code correctly for a
# "normal" return code but not for one generated by an unset variable.

main() {
  trap cleanup EXIT
  failure_without_exit_code
}

cleanup() {
  rv=$?
  echo "CLEANUP"
  exit $rv
}

failure_without_exit_code() {
    echo ${UNSET_VARIABLE}
}

failure_with_exit_code() {
  rm nonexistent_file_1234
}

main
